# services:
#   web:
#     build: .
#     container_name: Jinjer-web
#     restart: always
#     command: bash entrypoint.sh
#     volumes:
#       - .:/app
#       - ./static:/app/static
#       - ./media:/app/media
#     ports:
#       - 8000:8000
#     depends_on:
#       - db
#     environment:
#       - DATABASE_HOST=db
#       - DATABASE_NAME=database
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=21232123

#   db:
#     image: postgres
#     container_name: Jinjer-db
#     restart: always
#     environment:
#       POSTGRES_DB: database
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: 21232123
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data:

services:
  web:
    build: .
    container_name: Jinjer-web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - 8081:8000  # Изменён внешний порт для веб-сервера
    depends_on:
      - db
      - rabbitmq
      - celery
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=21232123
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

  db:
    image: postgres
    container_name: Jinjer-db
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 21232123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:management
    container_name: Jinjer-rabbitmq
    restart: always
    ports:
      - 5673:5672  # Изменён внешний порт для RabbitMQ
      - 15673:15672  # Изменён порт для RabbitMQ management UI

  celery:
    build: .
    container_name: Jinjer-celery
    restart: always
    command: celery -A Jinjer worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=21232123
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

volumes:
  postgres_data:
